output/csv: fix dedup logic
sigrokproject/libsigrok pull request #158
Opened 2021-09-06 23:45 UTC by kelvie

This fixes the dedup logic in the csv output to:
- dedup across samples (much like the vcd output module)
- not print two values for every group of samples

`previous_sample` was being freed every receive, and so it was
impossible to dedup across multiple receives, which would cause many
rows even when the level hasn't changed when using high sample rates.

There was also a range check for `i` that makes it so that two values
will always skip the dedup check, again spamming rows even when the
level hasn't changed.

2021-09-06 23:46 UTC, kelvie commented on src/output/csv.c
> -	g_free(ctx->previous_sample);
This is free'd in the cleanup function so I don't think there's a memory leak.

2024-10-14 10:11 UTC, biot requested changes
I'm sorry your PR didn't get reviewed sooner, I hope you're still interested in fixing the CSV output module.

However your fixes need some work.

2024-10-14 10:11 UTC, biot commented on src/output/csv.c
> +				sample_time_dbl = ctx->out_sample_count - 1;
You're correct that the sample count needs to be incremented earlier, but why does the `- 1` happen at all?

2024-10-14 19:59 UTC, kelvie commented
Hello, unfortunately that thing happened where I've forgotten how I encountered this fix after 3 years . I'll close this, but yeah feel free to incorporate these changes if they're helpful (I don't need attribution).

2024-10-14 19:59 UTC, closed without merging