SDM3055 Support
sigrokproject/libsigrok pull request #204
Opened 2022-12-18 07:32 UTC by Electro707

This PR adds support for the SDM3055 multimeter as an scpi-dmm device.

All functionality was tested with `smuview` with TCP. The log out of it looks right as well. I also tested it with USB initially (a while ago), but I can re-test it again before this gets merged.

I will probably add the other two sibling meters (SDM3045X and the SDM3065X), but I will have no way to test those unless someone wants to volunteer to do so, in which case it is much appreciated.

2023-02-17 22:05 UTC, knarfS requested changes

2023-02-17 22:05 UTC, knarfS commented on src/hardware/scpi-dmm/api.c
> +	{ SR_MQ_CAPACITANCE, 0, "CAP", "CAP", NO_DFLT_PREC, },
All entries are missing the 6th property, probably `FLAGS_NONE` in your case.

2023-02-17 22:05 UTC, knarfS commented on src/hardware/scpi-dmm/api.c
> +		0, 0,
The last 6 properties for this struct are missing

2023-02-17 22:07 UTC, knarfS commented
Hey there, your PR looks good, but is missing some properties for the structs.

2023-02-17 22:09 UTC, knarfS commented
Also, it would be great if you could squash all commits into one

2023-02-20 03:33 UTC, Electro707 commented
Added the missing properties, as well as squashed the changes

2023-02-20 07:06 UTC, knarfS approved these changes
Thanks, looking good!

2023-02-25 10:12 UTC, knarfS commented
One last thing I just recognized: Could you please move the new UDEV rule up? The rules are sorted alphabetically by vendor name.

Once that is done, the PR can be merged.

2023-02-27 05:08 UTC, Electro707 commented
> One last thing I just recognized: Could you please move the new UDEV rule up? The rules are sorted alphabetically by vendor name.
> 
> Once that is done, the PR can be merged.

Moved the UDEV rule up with the rest of the Siglent stuff

2023-02-27 20:41 UTC, knarfS commented
Thanks Jamal!
Do you mind if I split your single commit into three (one for the udev rule, one for scpi and one for the driver definition) before merging into master? Please let me know.
Cheers, Frank

2023-02-27 20:59 UTC, Electro707 commented
> Thanks Jamal! Do you mind if I split your single commit into three (one for the udev rule, one for scpi and one for the driver definition) before merging into master? Please let me know. Cheers, Frank

Absolutely, go for it!

2023-02-28 20:15 UTC, knarfS commented
Merged with commits 821266e, b35face and 5ab4f63. Unfortunately the synchronization from the sigrok repository to github isn't working at the moment, but here you can find the sigrok repo: https://sigrok.org/gitaction/libsigrok.git/0dea024..5ab4f63

I added a basic wiki page the the device: https://sigrok.org/wiki/Siglent_SDM3055

It would be great if you close the PR.

2023-03-01 17:18 UTC, Electro707 commented
Great, thanks!
If I have time I might edit that Wiki page to add hardware info and pictures.

2023-03-01 17:18 UTC, closed without merging

2023-03-01 19:50 UTC, knarfS commented
> If I have time I might edit that Wiki page to add hardware info and pictures.

That would be great!