Add long command processing time for Velleman PS3005DV1.3
sigrokproject/libsigrok pull request #210
Opened 2023-02-14 15:29 UTC by pilatomic

The Velleman PS3005D V1.3 power supply ( driver korad_kaxxxxp ) seems to
have a quirky RS232 interface, that requires waiting a longer time after
some commands before being allowed to send a new command.
Failing to respect this delay means the new command will NOT be executed.
This is especially problematic as the actual driver would report "0.000" value
for current when the power supply failed to answer the IOUT? request,
despite the output current being non zero.

This commit adds a quirk for this specific revision, and introduces a longer
delay for the affected commands ( STATUS? + any set command ).
The behavior is unchanged for other models.

2023-02-17 22:23 UTC, knarfS requested changes
Thanks for your PR.
Apart from two style nits, everything looks good to me.

2023-02-17 22:23 UTC, knarfS commented on src/hardware/korad-kaxxxxp/protocol.c
> +	if(devc->model->quirks & KORAD_QUIRK_LONG_PROCESSING_TIME &&
Style nit: Space between `if` and `(`

2023-02-17 22:23 UTC, knarfS commented on src/hardware/korad-kaxxxxp/protocol.c
> +	if(target == KAXXXXP_STATUS)
Style nit: space between `if` and `(`

2023-02-18 10:16 UTC, pilatomic commented
Thank you for your review, I have fixed the 2 lines you pointed out.

2023-02-26 09:59 UTC, closed without merging