Add driver for GW Instek PSP series
sigrokproject/libsigrok pull request #227
Opened 2023-10-31 21:39 UTC by ettom

The protocol is described in the manual, available [here](https://www.gwinstek.com/en-global/products/downloadSeriesDownNew/7327/1426).

Generally, everything seems to work well. One annoying limitation of the protocol/device is that it uses the same field for reporting both the actual voltage and the target voltage. This means that querying the target voltage is not possible while the output is enabled or the device is in CC mode. I did implement a heuristic to work around this as best as I could, but one corner case remains - when SmuView is launched while the output is enabled and the device is in CC mode, the target voltage will be reported as 0.00V until the output is turned on (at which point the target voltage will be updated according to the one set on the device), or until a new target voltage is set via the UI. I think that this limitation is acceptable if properly documented.

2024-09-27 21:04 UTC, biot requested changes

2024-09-27 21:15 UTC, biot commented
Sorry about the long delay in getting this reviewed, I hope you still want to get this driver merged. The code looks good, aside from the minor changes. Seems like a challenging device to write a driver for.

2024-10-09 11:00 UTC, ettom commented on src/hardware/gwinstek-psp/api.c
> +		return NULL;
As far as I can tell, the only way would be to set the voltage or current limit to the maximum value (there are dedicated commands for this) and infer the model from that. Unfortunately, I couldn't get the vendor-provided software to work at all, so I can't verify if this is what it does. In any case, I think this method would be unacceptable, as the software shouldn't change the output values without explicit user input.

2024-10-10 00:19 UTC, biot requested changes

2024-10-10 13:17 UTC, ettom commented on src/hardware/gwinstek-psp/protocol.c
> +	g_usleep(500 * 1000);
Good point.

I'm not completely sure why, but with 15ms, I could pretty reliably cause the wrong terminator to be detected - device is in URPSP1, but the driver would report URPSP2. I'm guessing the device might not be transmitting at a constant rate or has some delays? With a 17+ms delay, it was solid. So I've set it to 20ms, for just a bit of safety net.

2024-10-10 13:36 UTC, biot approved these changes

2024-10-16 21:48 UTC, abraxa commented
Merged as https://sigrok.org/gitaction/libsigrok.git/bcf21cc..e938e2d, thank you for your contribution!

2024-10-16 21:48 UTC, closed without merging